spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/matrix?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
    solr:
      host: http://127.0.0.1:8983/solr
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
logging:
  level:
    root: INFO
    io:
      github:
        woodenlock:
          gaia: DEBUG
    org:
      elasticsearch:
        client:
          RestClient: ERROR
      springframework:
        data:
          solr:
            core: DEBUG
          mongodb:
            core: DEBUG
          elasticsearch:
            core: DEBUG
  config: classpath:logback-spring.xml
dynamic:
  module:
    includes:
      - /io/github/woodenlock/gaia/example/model/entity/**
    preferences:
      - component: dao
        persistence: Solr
        order: 0
        path: /dao/solr
      - component: view-object
        order: 0
        customizes: {"ignoreFields":["deleted"]}
      - component: controller
        order: 0
        customizes: {"requestSuffix":"api"}